package parser;


import java.io.IOException;

import source.Source;

/** 
 * class CUPScanner - To allow Lexer to be public.
 * @version $Id: CUPScanner.java 9 2013-04-10 05:36:09Z ianh $
 * The Lexer class generated by JFlex is not public
 * and hence isn't visible outside the parser package.
 * This little interface makes its constructor visible
 * outside the parser package.
 */

public class CUPScanner extends Lexer {

    public CUPScanner( Source s ) throws IOException 
    {
        super(s);
    }
}
