
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 18 11:35:37 EST 2015
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface CUPToken {
  /* terminals */
  public static final int DIVIDE = 10;
  public static final int LBRACKET = 23;
  public static final int KW_PROCEDURE = 33;
  public static final int EQUALS = 11;
  public static final int PERIOD = 18;
  public static final int KW_DO = 28;
  public static final int LPAREN = 2;
  public static final int GREATER = 16;
  public static final int KW_CONST = 27;
  public static final int LESS = 15;
  public static final int MINUS = 8;
  public static final int RPAREN = 3;
  public static final int KW_RECORD = 35;
  public static final int SEMICOLON = 4;
  public static final int GEQUALS = 14;
  public static final int RANGE = 17;
  public static final int LEQUALS = 13;
  public static final int NEQUALS = 12;
  public static final int COMMA = 19;
  public static final int KW_WRITE = 40;
  public static final int PLUS = 7;
  public static final int KW_TYPE = 37;
  public static final int ASSIGN = 6;
  public static final int KW_NEW = 32;
  public static final int KW_CALL = 26;
  public static final int EOF = 0;
  public static final int RBRACKET = 24;
  public static final int KW_BEGIN = 25;
  public static final int error = 1;
  public static final int LCURLY = 21;
  public static final int NUMBER = 43;
  public static final int KW_IF = 31;
  public static final int RCURLY = 22;
  public static final int TIMES = 9;
  public static final int COLON = 5;
  public static final int ILLEGAL = 41;
  public static final int KW_END = 30;
  public static final int KW_ELSE = 29;
  public static final int KW_READ = 34;
  public static final int KW_VAR = 38;
  public static final int KW_WHILE = 39;
  public static final int KW_THEN = 36;
  public static final int POINTER = 20;
  public static final int IDENTIFIER = 42;
}

